// <auto-generated />
using System;
using DriveSyncPing.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriveSyncPing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907145337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.AppConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncFolderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncFolderId");

                    b.ToTable("SyncFiles");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncFolders");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SyncFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SyncFileId");

                    b.HasIndex("SyncJobId");

                    b.ToTable("SyncOperations");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncFile", b =>
                {
                    b.HasOne("DriveSyncPing.Domain.Entities.SyncFolder", "SyncFolder")
                        .WithMany("Files")
                        .HasForeignKey("SyncFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncFolder");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncOperation", b =>
                {
                    b.HasOne("DriveSyncPing.Domain.Entities.SyncFile", "SyncFile")
                        .WithMany()
                        .HasForeignKey("SyncFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DriveSyncPing.Domain.Entities.SyncJob", "SyncJob")
                        .WithMany("Operations")
                        .HasForeignKey("SyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncFile");

                    b.Navigation("SyncJob");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncFolder", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("DriveSyncPing.Domain.Entities.SyncJob", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
